CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms (

    id SERIAL PRIMARY KEY,

    room_id VARCHAR(255)
    UNIQUE NOT NULL,

    code TEXT NOT NULL,

    language VARCHAR(50)
    NOT NULL,

    updated_at TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
);